spring:
  thymeleaf:
    enabled: true
  data:
    jdbc:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo_note
    username: postgres
    password: postgres
  output:
    ansi:
      enabled: detect
  security:
    user:
      name: "test"
  profiles:
    active: dev
logging:
  pattern:
    console: "[%red(%thread)] [%green(level)] [%blue(%logger{36}):%yellow(%line)] %magenta(%method) - %msg%n"
  main:
    allow-circular-references: true

server:
      port: 8888