version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rsDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
